# utils/config.py

SUPABASE_URL = "https://itgwoviyzqdeuuczcztb.supabase.co"
SUPABASE_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0Z3dvdml5enFkZXV1Y3pjenRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODkwOTQsImV4cCI6MjA1ODg2NTA5NH0.NNGfVlzLIJGPMDxzOf3CShtd2BzGEscwD0pSD0elb_A"
